/// @description stuff that gets created immediately for the textbox
// You can write your code in this editor
page = 0;
text[0] = "Bacon ipsum dolor amet jowl chicken biltong t-bone spare ribs pork picanha. Chicken alcatra t-bone pork belly, landjaeger ham ribeye turkey sausage cupim spare ribs salami andouille. Ham frankfurter ground round, corned beef rump alcatra meatball cow ham hock pork loin bacon pig hamburger strip steak. Bacon corned beef drumstick, filet mignon biltong strip steak pancetta landjaeger pork belly."
		+ "Ground round corned beef andouille strip steak prosciutto ham hock chicken short loin pork chop bacon. Jowl picanha ball tip, pastrami strip steak burgdoggen pork chop. Tenderloin flank frankfurter jowl, pancetta boudin chuck meatloaf pastrami pork loin fatback strip steak t-bone prosciutto. Pork chop picanha pancetta leberkas doner kevin, andouille beef corned beef meatball cow. Pig capicola ham, chicken beef shoulder ham hock pork chop venison tri-tip ball tip turkey shank leberkas."
		+ "Alcatra doner ball tip, turducken drumstick fatback corned beef t-bone short ribs salami tail tri-tip shankle ribeye turkey. Pastrami shankle salami swine. Sausage shoulder alcatra turducken, t-bone beef drumstick bacon pastrami tenderloin ground round kielbasa beef ribs hamburger. Boudin tenderloin biltong hamburger pig. Tail beef beef ribs jerky doner kevin spare ribs t-bone landjaeger.";

text[1] = "Sit there wishing I had a real relationship with someone. Wish I could hang out with my best friend watching a movie or playing a board game or showing her a cool video game or go hiking or go to dinner or go to a baseball game or I don't care what just spend time with my best friend. I don't care who, just someone who I legitimately enjoy spending time with. J, R, L, C, A, I don't care just someone. Don't take that as I want to date any of them, just that I enjoy spending time with them and if I suddenly found myself in a happy relationship with them I wouldn't be upset."
		+ "Yay.... at least I basically don't feel anything for her anymore? I mean, yes I see a picture of her and think \"Wouldn't that have been nice.\" I don't sit here thinking about her all the time wanting to be with her, though. There's nobody else who I have a real interest in where there's a nonzero probability of it ever working.";
boxWidth = sprite_get_width(sprite_placementTextBox);
stringHeight = string_height(text[page]);